### PR TITLE
Port upstream regtest driver script

### PR DESCRIPTION
**Pull request by domob1812**
This ports over the `test_runner.py` driver script for regtests from modern Bitcoin Core, and replaces the ad-hoc `run-tests.sh` script with it.  The new driver script has a lot more features, for instance a nice summary of the test results, timings of the individual tests, and support for running tests in parallel.

In order to use the new driver script, we also had to clean up a lot of quirks in some of the individual tests, convert them to properly use the test framework, and things like that.

Note that until #26 and #27 are merged (which are independent from this, although probably will create trivial merge conflicts in the `run-tests.sh` file), the two tests from those PRs will fail.

### CODE REVIEW

**Comment by domob1812** [comment]
For testing, I've merged all three PRs together into b4c2c258144c12ecea639b1f4ba82e5f97d4b325, and there indeed the `test_runner.py` passes completely.  (But this is just experimental, and the three PRs should instead be merged by themselves.)

**Comment by domob1812** [comment]
With the default of running four tests in parallel, the regtests now pass in about 130s for me rather than 330s when running them sequentially (including the fixed `smartfees.py` test, which takes by itself a long time).  This can likely be reduced quite a lot further by strategically ordering the tests in the driver script rather than the alphabetical order that is there now (long-running tests should be near the top, so they run in parallel to others).

**Comment by galpHub** [comment]
Apologies for the revert in #30, meant to pull them in the right order. I'll revert the squashed revert after the other two PRs have been merged in successfully.

**Comment by galpHub** [comment]
Fixed in a324cbbd

**Pull request merged**
