### PR TITLE
Clean up and optimise masternode ranking computations

### PR DESCRIPTION
**Pull request by domob1812**
This contains a lot of cleanups (including removal of dead code) for the general rank computation of masternodes.  In the last commit, we also introduce a cache of the top-20 masternodes by rank for the last 2'500 blocks.  This is enough to drastically reduce CPU usage during initial mnsync (e.g. after starting the node up), by avoiding lots of redundant masternode score calls.

### CODE REVIEW

**Review by galpHub — COMMENTED** [review]
Observations:
1. Before returning the rank, it should check the masternode directly because it might have gotten cached but died before the reward would have been claimed.
2. Since the cache is by blockheight, under a reorg (because mn rewards are forward looking) there's a chance that the wrong rewards get assigned. So we need to have an additional check when querying the cache that the blockhash at the given height of the current chain matches the blockhash of the cached blockheight

**Comment by domob1812** [comment]
Thanks for the feedback!  I've now added three more changes, which should make the cache more robust:
- Cache entries time out after five minutes
- When the masternode sync is reset / restarted, the cache is cleared out as well
- Before accepting a masternode payment as valid, explicitly double-check that the node is active at the moment

**Review by galpHub — CHANGES_REQUESTED** [review]
Regarding the timeout in 3a5deb134c7335d4956d7aa6537f135c169fa419, it seems like you've set it to 5 minutes but masternode winners tend to get sent out 10 blocks ahead of schedule
`
if (!fLiteMode) {
        if (masternodeSync.RequestedMasternodeAssets > MASTERNODE_SYNC_LIST) {
            masternodePayments.ProcessBlock(GetHeight() + 10);
        }
}
`
So the timeout should be at least 10 minutes (longer most likely for the cache to be of benefit). Also not sure about doing explicit timeouts? We should be delegating to whoever is deciding that we need to re-compute the masternode data which in this case I believe is the global CMasternodeSync object on which Process() is called periodically

**Comment by domob1812** [comment]
> Regarding the timeout in [3a5deb1](https://github.com/galpHub/Divi/commit/3a5deb134c7335d4956d7aa6537f135c169fa419), it seems like you've set it to 5 minutes but masternode winners tend to get sent out 10 blocks ahead of schedule
> `if (!fLiteMode) { if (masternodeSync.RequestedMasternodeAssets > MASTERNODE_SYNC_LIST) { masternodePayments.ProcessBlock(GetHeight() + 10); } }`
> So the timeout should be at least 10 minutes (longer most likely for the cache to be of benefit). Also not sure about doing explicit timeouts? We should be delegating to whoever is deciding that we need to re-compute the masternode data which in this case I believe is the global CMasternodeSync object on which Process() is called periodically

I've added the timeouts just as an extra layer of safety, as I got the impression you'd prefer to have something like this in.  Five minutes are more than enough to fix initial sync, which was the main thing I noticed as being annoying (and also computing the rank 2x if it takes 10 minutes to sync is much better than doing it 50x or whatever for each incoming message); but of course if you think that 10 minutes would be better and still "safe enough", or if you think that e.g. the other change with clearing the cache during `CMasternodeSync::Reset` is sufficient, I'm of course happy to drop the timeout or adjust it.

**Comment by domob1812** [comment]
I've removed the timeout change now.

**Review by galpHub — APPROVED** [review]

**Pull request merged**
