### PR TITLE
Activation manager for BIP30-style forks

### PR DESCRIPTION
**Pull request by domob1812**
This refactors BIP30-style fork activation (signalling with block versoins):  Instead of a function `IsSuperMajority`, we now have a utility class `ActivationManager` that takes care of both the state of individual forks (for now, just a `TestDummy` fork is defined) as well as of enforcing minimal block versions as the network updates.

Strictly speaking this is by itself already a soft fork that activates automatically:  With this logic, the network will enforce any arbitrary block version as minimum that has been seen in at least 950 of the last 1'000 blocks; previously that was only the case for specifically scheduled block versions corresponding to implemented forks.  This is irrelevant in practice, though.

Since DIVI started the network already with block version 4 and various BIPs enforced from the start (BIP16, BIP30, BIP34, BIP66), we can also remove obsolete / always-on "conditional" activation for those to simplify the code.

### CODE REVIEW

**Comment by domob1812** [comment]
I've successfully synced DIVI from scratch on mainnet with this PR now (so the various changes did not affect compatibility especially to the very first blocks).

**Comment by galpHub** [comment]
Looks ok. Is there a reason you added the commit for the staking vault checks in this PR ? I'm a bit confused by that

**Comment by domob1812** [comment]
> Looks ok. Is there a reason you added the commit for the staking vault checks in this PR ? I'm a bit confused by that

The main reason is that I believe both of these changes to be quick to review and push, and so I combined them.  If you prefer to review & push the checks as a separate PR, I'm happy to spit it up.

**Comment by domob1812** [comment]
I've removed the coinstakes checking commit from #38 now.

**Comment by domob1812** [comment]
We'll use activation based on a timestamp instead to simplify this, as in #55.

**Pull request closed without merging**
